### ISSUE TITLE
Auto importer too aggressive where slow file transfers to cwa-ingest cause importer to try importing incomplete files

### ISSUE THREAD

**Issue by jmarmstrong1207** [crocodilestick/Calibre-Web-Automator#7]
It also seems that the script gets paused or crashes as this happens. Further adding files to the cwa-ingest folder will not run the script anymore. Slow file transfers will happen if the user decides to directly download a book from the internet into the folder, or in my case, transfer a file from a personal PC to a separate server on the network.

This may be more easily fixed by continuously retrying to reimport the files that cause these errors. It doesn't seem to be a robust and long term solution though. Another good solution might be to add a button to manually start the book imports rather than only relying on auto imports.

Also there is a small typo in the debug messages bolded below. Instead of "sucsessfully", it should be "successfully" :
`[books-to-process]: New files sucsessfully moved/converted, the Ingest Folder has been emptied and is ready to go again.`

Here is a log file snippet. The EOF errors and "File is not a zip file" seems to indicate it being due to slow file transfers:
```
[books-to-process]: New files sucsessfully moved/converted, the Ingest Folder has been emptied and is ready to go again.
Failed to render /tmp/calibre_7.15.0_tmp_jwtye3gb/dgw9nkzm_epub_meta/index_split_000.html with errors:
Traceback (most recent call last):
  File "calibre/utils/ipc/simple_worker.py", line 53, in run
  File "calibre/utils/ipc/__init__.py", line 22, in eintr_retry_call
  File "multiprocessing/connection.py", line 249, in recv
  File "multiprocessing/connection.py", line 413, in _recv_bytes
  File "multiprocessing/connection.py", line 382, in _recv
EOFError

Traceback (most recent call last):
  File "calibre/ebooks/metadata/epub.py", line 159, in get_zip_reader
  File "calibre/utils/zipfile.py", line 774, in __init__
  File "calibre/utils/zipfile.py", line 809, in _GetContents
  File "calibre/utils/zipfile.py", line 824, in _RealGetContents
calibre.utils.zipfile.BadZipfile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 481, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 177, in get_metadata
  File "calibre/ebooks/metadata/epub.py", line 215, in get_metadata
  File "calibre/ebooks/metadata/epub.py", line 162, in get_zip_reader
  File "calibre/utils/localunzip.py", line 266, in __init__
  File "calibre/utils/localunzip.py", line 242, in _extractall
ValueError: Not a ZIP file
The following books were not added as they already exist in the database (see --duplicates option or --automerge option):
  A Knight of the Seven Kingdoms
  Alya Sometimes Hides Her Feelings in Russian, Vol. 3
    /etc/calibre-web-automator/cwa-import/A Knight of the Seven Kingdoms - George R. R. Martin.epub
    /etc/calibre-web-automator/cwa-import/Alya Sometimes Hides Her Feelings in Russian, Vol. 3.epub
Added book ids: 9
[new-book-detector] Added Ascendance of a Bookworm Short Story Collection vol 1 『Premium Ver』.epub to Calibre database
[new-book-detector]: Removing Ascendance of a Bookworm Short Story Collection vol 1 『Premium Ver』.epub from import folder...
rm: cannot remove '/etc/calibre-web-automator/cwa-import/*': No such file or directory
[new-book-detector]: Ascendance of a Bookworm Short Story Collection vol 1 『Premium Ver』.epub sucsessfully moved/converted, the Ingest Folder has been emptied and is ready
[books-to-process]: New files detected - Ascendance of a Bookworm Part 3 volume 2 『Premium Ver』.epub
[new-book-detector]: New file detected: Ascendance of a Bookworm Part 3 volume 2 『Premium Ver』.epub

[new-book-processor]: Found 1 epub file(s) from the most recent download.
[new-book-processor]: Moving resulting files to calibre-web import folder...

[new-book-processor]: Moving /cwa-book-ingest/Ascendance of a Bookworm Part 3 volume 2 『Premium Ver』.epub...
[new-book-processor]: Copied 1 epub file(s) to calibre-web import folder.
[new-book-processor]: Processing of new files completed in 0.02 seconds.


[books-to-process]: New files sucsessfully moved/converted, the Ingest Folder has been emptied and is ready to go again.
Failed to render /tmp/calibre_7.15.0_tmp_0npmjdl0/f4x5s959_epub_meta/index_split_000.html with errors:
Traceback (most recent call last):
  File "calibre/utils/ipc/simple_worker.py", line 53, in run
  File "calibre/utils/ipc/__init__.py", line 22, in eintr_retry_call
  File "multiprocessing/connection.py", line 249, in recv
  File "multiprocessing/connection.py", line 413, in _recv_bytes
  File "multiprocessing/connection.py", line 382, in _recv
EOFError

Traceback (most recent call last):
  File "calibre/ebooks/metadata/epub.py", line 159, in get_zip_reader
  File "calibre/utils/zipfile.py", line 774, in __init__
  File "calibre/utils/zipfile.py", line 809, in _GetContents
  File "calibre/utils/zipfile.py", line 824, in _RealGetContents
calibre.utils.zipfile.BadZipfile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 481, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 177, in get_metadata
  File "calibre/ebooks/metadata/epub.py", line 215, in get_metadata
  File "calibre/ebooks/metadata/epub.py", line 162, in get_zip_reader
  File "calibre/utils/localunzip.py", line 266, in __init__
  File "calibre/utils/localunzip.py", line 242, in _extractall
ValueError: Not a ZIP file
Added book ids: 1, 2, 3, 4
[new-book-detector] Added Ascendance of a Bookworm Part 3 volume 2 『Premium Ver』.epub to Calibre database
[new-book-detector]: Removing Ascendance of a Bookworm Part 3 volume 2 『Premium Ver』.epub from import folder...
rm: cannot remove '/etc/calibre-web-automator/cwa-import/*': No such file or directory
[new-book-detector]: Ascendance of a Bookworm Part 3 volume 2 『Premium Ver』.epub sucsessfully moved/converted, the Ingest Folder has been emptied and is ready
[books-to-process]: New files detected - Ascendance of a Bookworm
[new-book-detector]: New file detected: Ascendance of a Bookworm Fanbook vol 1 Premium.epub

[new-book-processor]: Found 1 epub file(s) from the most recent download.
[new-book-processor]: Moving resulting files to calibre-web import folder...

[new-book-processor]: Moving /cwa-book-ingest/Ascendance of a Bookworm/Ascendance of a Bookworm Fanbook/EPUB/Ascendance of a Bookworm Fanbook vol 1 Premium.epub...
[new-book-processor]: Copied 1 epub file(s) to calibre-web import folder.
[new-book-processor]: Processing of new files completed in 0.00 seconds.
Traceback (most recent call last):
  File "/etc/calibre-web-automator/new-book-processor.py", line 92, in <module>


    main()
  File "/etc/calibre-web-automator/new-book-processor.py", line 41, in main
    empty_to_process_folder()
  File "/etc/calibre-web-automator/new-book-processor.py", line 88, in empty_to_process_folder
    os.remove(f)
IsADirectoryError: [Errno 21] Is a directory: '/cwa-book-ingest/Ascendance of a Bookworm'
[books-to-process]: New files sucsessfully moved/converted, the Ingest Folder has been emptied and is ready to go again.
Failed to render /tmp/calibre_7.15.0_tmp_fvzid0bu/z_ki6rxz_epub_meta/index_split_000.html with errors:
Traceback (most recent call last):
  File "calibre/utils/ipc/simple_worker.py", line 53, in run
  File "calibre/utils/ipc/__init__.py", line 22, in eintr_retry_call
  File "multiprocessing/connection.py", line 249, in recv
  File "multiprocessing/connection.py", line 413, in _recv_bytes
  File "multiprocessing/connection.py", line 382, in _recv
EOFError

Traceback (most recent call last):
  File "calibre/ebooks/metadata/epub.py", line 159, in get_zip_reader
  File "calibre/utils/zipfile.py", line 774, in __init__
  File "calibre/utils/zipfile.py", line 809, in _GetContents
  File "calibre/utils/zipfile.py", line 824, in _RealGetContents
calibre.utils.zipfile.BadZipfile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 481, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 177, in get_metadata
  File "calibre/ebooks/metadata/epub.py", line 215, in get_metadata
  File "calibre/ebooks/metadata/epub.py", line 162, in get_zip_reader
  File "calibre/utils/localunzip.py", line 266, in __init__
  File "calibre/utils/localunzip.py", line 242, in _extractall
ValueError: Not a ZIP file
Traceback (most recent call last):
  File "calibre/ebooks/metadata/epub.py", line 159, in get_zip_reader
  File "calibre/utils/zipfile.py", line 774, in __init__
  File "calibre/utils/zipfile.py", line 809, in _GetContents
  File "calibre/utils/zipfile.py", line 824, in _RealGetContents
calibre.utils.zipfile.BadZipfile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 481, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 177, in get_metadata
  File "calibre/ebooks/metadata/epub.py", line 215, in get_metadata
  File "calibre/ebooks/metadata/epub.py", line 162, in get_zip_reader
  File "calibre/utils/localunzip.py", line 266, in __init__
  File "calibre/utils/localunzip.py", line 242, in _extractall
ValueError: Not a ZIP file
Added book ids: 5, 6, 7, 8, 9
[new-book-detector] Added Ascendance of a Bookworm Fanbook vol 1 Premium.epub to Calibre database
[new-book-detector]: Removing Ascendance of a Bookworm Fanbook vol 1 Premium.epub from import folder...
rm: cannot remove '/etc/calibre-web-automator/cwa-import/*': No such file or directory
[new-book-detector]: Ascendance of a Bookworm Fanbook vol 1 Premium.epub sucsessfully moved/converted, the Ingest Folder has been emptied and is ready
```

**Comment by crocodilestick** [comment]
Hi James, yeah I've been meaning to rework the import system, it's the first thing I wrote for the project and it's barely been touched since so I have been working on a more robust solution, will be fixed in a coming update 👍
